name: Create Docs

on:
  push:
    branches:
      - master
      - pre
      - exp
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install DocFX
        run: choco install -y docfx

      - name: Use README.md as index.md
        run: cp README.md Packages/com.careboo.unity-algorand-sdk/Documentation/index.md

      - name: Build
        run: docfx Packages/com.careboo.unity-algorand-sdk/Documentation/docfx.json

      - name: Upload site artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site
          path: Packages/com.careboo.unity-algorand-sdk/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Download Docs site artifact
        uses: actions/download-artifact@v1
        with:
          name: _site

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
