name: Format check

on:
  pull_request:

jobs:
  dotnet-format:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add Problem Matcher
        uses: renanrcp/dotnet-format-problem-matcher@v.1.3.1

      - name: Get Changed C# Files
        uses: tj-actions/changed-files@v16
        id: changed_csharp_files
        with:
          files: |
            *.cs

      - name: Run dotnet format
        id: format
        run: dotnet format whitespace . --folder --include ${{ steps.changed_csharp_files.outputs.all_changed_files }}
