name: Create Release

on:
  push:
    branches:
      - main
      - pre
      - exp
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x.x"

jobs:
  release:
    name: Release New Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Semantic release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move README.md
        if: steps.semantic.outputs.new_release_published == 'true'
        run: mv README.md Packages/com.careboo.unity-algorand-sdk/README.md

      - name: Move LICENSE.md
        if: steps.semantic.outputs.new_release_published == 'true'
        run: mv LICENSE.md Packages/com.careboo.unity-algorand-sdk/LICENSE.md

      - name: Move Documentation folder
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          mv Packages/com.careboo.unity-algorand-sdk/Documentation Packages/com.careboo.unity-algorand-sdk/~Documentation
          rm Packages/com.careboo.unity-algorand-sdk/Documentation.meta
          rm Packages/com.careboo.unity-algorand-sdk/~Documentation/**/*.meta

      - name: Replace Version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: ./scripts/replace_version
        env:
          VERSION: ${{ steps.semantic.outputs.new_release_version }}

      - name: Setup npm for npmjs
        uses: actions/setup-node@v2
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/

      - name: Publish to npmjs
        if: steps.semantic.outputs.new_release_published == 'true'
        run: ./scripts/release_npmjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup npm for GPR
        uses: actions/setup-node@v2
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          registry-url: "https://npm.pkg.github.com"

      - name: Publish to GPR
        if: steps.semantic.outputs.new_release_published == 'true'
        run: ./scripts/release_gpr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_docs:
    name: Build Docs
    needs: release
    runs-on: windows-latest
    strategy:
      matrix:
        tag: ["version", "branch"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: Get package version
        id: version
        if: ${{ matrix.tag == 'version' }}
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "Packages/com.careboo.unity-algorand-sdk/package.json"
          prop_path: "version"

      - name: Get branch
        id: branch
        if: ${{ matrix.tag == 'branch' }}
        run: echo "::set-output name=name::${GITHUB_REF#refs/heads/}"

      - name: Install DocFX
        run: choco install -y docfx

      - name: Use README.md as index.md
        run: cp README.md Packages/com.careboo.unity-algorand-sdk/Documentation/index.md

      - name: Copy LICENSE to package
        run: cp LICENSE.md Packages/com.careboo.unity-algorand-sdk/LICENSE.md

      - name: Update sitemap with version
        if: ${{ matrix.tag == 'version' }}
        uses: jossef/action-set-json-field@v1
        with:
          file: Packages/com.careboo.unity-algorand-sdk/Documentation/docfx.json
          field: build.sitemap.baseUrl
          value: https://CareBoo.github.io/unity-algorand-sdk/${{ steps.version.outputs.prop }}/

      - name: Update sitemap with branch
        if: ${{ matrix.tag == 'branch' }}
        uses: jossef/action-set-json-field@v1
        with:
          file: Packages/com.careboo.unity-algorand-sdk/Documentation/docfx.json
          field: build.sitemap.baseUrl
          value: https://CareBoo.github.io/unity-algorand-sdk/${{ steps.branch.outputs.branch }}/

      - name: Build
        run: docfx Packages/com.careboo.unity-algorand-sdk/Documentation/docfx.json

      - name: Upload site artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site_${{ matrix.tag }}
          path: Packages/com.careboo.unity-algorand-sdk/_site

  deploy_docs_version:
    name: Deploy Version Docs
    needs: build_docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: Download Docs site artifact
        uses: actions/download-artifact@v1
        with:
          name: _site_version

      - name: Get package version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "Packages/com.careboo.unity-algorand-sdk/package.json"
          prop_path: "version"

      - name: Deploy Docs Version
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site_version
          destination_dir: ${{ steps.version.outputs.prop }}

  deploy_docs_branch:
    name: Deploy Branch Docs
    needs: build_docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: Download Docs site artifact
        uses: actions/download-artifact@v1
        with:
          name: _site_branch

      - name: Get branch
        id: branch
        run: echo "::set-output name=name::${GITHUB_REF#refs/heads/}"

      - name: Deploy Docs Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site_branch
          destination_dir: ${{ steps.branch.outputs.name }}
