name: Create Release

on:
  push:
    branches:
      - main
      - pre
      - exp
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x.x"

jobs:
  semantic_release:
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - uses: actions/checkout@v2

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_npm:
    name: Publish Package to ${{ matrix.registry }}
    runs-on: ubuntu-latest
    needs: semantic_release
    if: needs.semantic_release.outputs.new_release_published == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - registry: https://registry.npmjs.org/
            scope: ""
            token: NPM_TOKEN
          - registry: https://npm.pkg.github.com/
            scope: "@careboo"
            token: GITHUB_TOKEN
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: Remove symlinks
        run: sed -i '' Documentation\~/**/*

      - name: Setup npm
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: ${{ matrix.registry }}

      - name: Publish to ${{ matrix.registry }}
        run: npm publish --access=public --registry=${{ matrix.registry }}${{ matrix.scope }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.token] }}

  build_docs:
    name: Build Docs
    needs: semantic_release
    runs-on: windows-latest
    strategy:
      matrix:
        tag: ["version", "branch"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: Get package version
        id: version
        if: ${{ matrix.tag == 'version' }}
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"

      - name: Get branch
        id: branch
        if: ${{ matrix.tag == 'branch' }}
        run: echo "::set-output name=name::${GITHUB_REF#refs/heads/}"

      - name: Install DocFX
        run: choco install -y docfx

      - name: Update sitemap with version
        if: ${{ matrix.tag == 'version' }}
        uses: jossef/action-set-json-field@v1
        with:
          file: .docfx/docfx.json
          field: build.sitemap.baseUrl
          value: https://CareBoo.github.io/unity-algorand-sdk/${{ steps.version.outputs.prop }}/

      - name: Update sitemap with branch
        if: ${{ matrix.tag == 'branch' }}
        uses: jossef/action-set-json-field@v1
        with:
          file: .docfx/docfx.json
          field: build.sitemap.baseUrl
          value: https://CareBoo.github.io/unity-algorand-sdk/${{ steps.branch.outputs.branch }}/

      - name: Build
        run: docfx .docfx/docfx.json

      - name: Upload site artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site_${{ matrix.tag }}
          path: _site

  deploy_docs_version:
    name: Deploy Version Docs
    needs: build_docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: Download Docs site artifact
        uses: actions/download-artifact@v1
        with:
          name: _site_version

      - name: Get package version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"

      - name: Deploy Docs Version
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site_version
          destination_dir: ${{ steps.version.outputs.prop }}

  deploy_docs_branch:
    name: Deploy Branch Docs
    needs: deploy_docs_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: Download Docs site artifact
        uses: actions/download-artifact@v1
        with:
          name: _site_branch

      - name: Get branch
        id: branch
        run: echo "::set-output name=name::${GITHUB_REF#refs/heads/}"

      - name: Deploy Docs Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site_branch
          destination_dir: ${{ steps.branch.outputs.name }}
