name: Unity Tests

on:
  pull_request:
    paths:
      - "**.cs"
      - "**.dll"
      - "Unity.AlgoSdk/Packages/packages-lock.json"
      - "**/Plugins/**"

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2020 }}

jobs:
  testAllModes:
    name: Test ${{ matrix.unityVersion}} ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        unityVersion: [2020.3.30f1, 2021.2.13f1]
        targetPlatform:
          # - mac-mono
          # - windows-mono
          - linux-il2cpp
          # - ios
          # - android
          # - webgl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash
      - name: Cache Library
        uses: actions/cache@v2.1.1
        with:
          path: Unity.AlgoSdk/Library
          key: Library-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            Library-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.unityVersion }}-
      - run: echo "::set-output name=result::+CareBoo.AlgoSdk*,-CareBoo.AlgoSdk*.Tests,-CareBoo.AlgoSdk*.Samples*"
        id: assemblyFilters
      - uses: game-ci/unity-test-runner@v2
        id: tests
        with:
          projectPath: ./Unity.AlgoSdk
          artifactsPath: TestResults
          customParameters: -batchMode -burst-disable-compilation -enableCodeCoverage -coverageOptions generateAdditionalMetrics;enableCyclomaticComplexity;assemblyFilters:${{ steps.assemblyFilters.outputs.result }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          useHostNetwork: true
          customImage: unityci/editor:${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}-0
          checkName: Test Results ${{ matrix.unityVersion }} ${{ matrix.targetPlatform }}
      - name: Upload Test Results Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Unity ${{ matrix.unityVersion }} ${{ matrix.targetPlatform }} Test Results
          path: ${{ steps.tests.outputs.artifactsPath }}
      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Unity ${{ matrix.unityVersion }} ${{ matrix.targetPlatform }} Code Coverage
          path: Unity.AlgoSdk/CodeCoverage
      - name: Upload PlayMode Test Coverage Report
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: Unity.AlgoSdk/CodeCoverage/workspace-opencov/PlayMode/TestCoverageResults_0000.xml
      - name: Upload EditMode Test Coverage Report
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: Unity.AlgoSdk/CodeCoverage/workspace-opencov/EditMode/TestCoverageResults_0000.xml
