name: Unity Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2020 }}

jobs:
  testAllModes:
    name: Test ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          # - StandaloneOSX
          # - StandaloneWindows64
          - StandaloneLinux64
          # - iOS
          # - Android
          # - WebGL

    steps:
      - name: Checkout Algorand sandbox
        uses: actions/checkout@v2
        with:
          repository: algorand/sandbox
          path: sandbox
      - name: Run Algorand sandbox services
        run: |
          cd sandbox
          script -e -c "./sandbox up -v release"
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash
      - name: Cache Library
        uses: actions/cache@v2.1.1
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-
      - run: ./scripts/coverageAssemblyFilters
        id: assemblyFilters
      - uses: game-ci/unity-test-runner@v2
        id: tests
        with:
          artifactsPath: TestResults
          customParameters: -batchMode -burst-disable-compilation -enableCodeCoverage -coverageOptions generateAdditionalMetrics;enableCyclomaticComplexity;assemblyFilters:${{ steps.assemblyFilters.outputs.result }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          useNetworkHost: true
      - name: Upload Test Results Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: ${{ steps.tests.outputs.artifactsPath }}
      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Code Coverage
          path: ./CodeCoverage
      - name: Upload PlayMode Test Coverage Report
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: ./CodeCoverage/workspace-opencov/PlayMode/TestCoverageResults_0000.xml
      - name: Upload EditMode Test Coverage Report
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: ./CodeCoverage/workspace-opencov/EditMode/TestCoverageResults_0000.xml
