name: Unity Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2020 }}

jobs:
  testAllModes:
    name: Test ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        unityVersion: [2020.3.27f1, 2021.2.9f1]
        targetPlatform:
          - mac-mono
          - windows-mono
          - linux-il2cpp
          - ios
          - android
          - webgl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash
      - name: Cache Library
        uses: actions/cache@v2.1.1
        with:
          path: Library
          key: Library-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            Library-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.unityVersion }}-
      - run: ./scripts/coverageAssemblyFilters
        id: assemblyFilters
      - uses: game-ci/unity-test-runner@v2
        id: tests
        with:
          artifactsPath: TestResults
          customParameters: -batchMode -burst-disable-compilation -enableCodeCoverage -coverageOptions generateAdditionalMetrics;enableCyclomaticComplexity;assemblyFilters:${{ steps.assemblyFilters.outputs.result }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          useNetworkHost: true
          customImage: unityci/editor:${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}-0
      - name: Upload Test Results Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Unity ${{ matrix.unityVersion }} ${{ matrix.targetPlatform }} Test Results
          path: ${{ steps.tests.outputs.artifactsPath }}
      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Unity ${{ matrix.unityVersion }} ${{ matrix.targetPlatform }} Code Coverage
          path: ./CodeCoverage
      - name: Upload PlayMode Test Coverage Report
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: ./CodeCoverage/workspace-opencov/PlayMode/TestCoverageResults_0000.xml
      - name: Upload EditMode Test Coverage Report
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: ./CodeCoverage/workspace-opencov/EditMode/TestCoverageResults_0000.xml
