name: Create .unitypackage

on:
  release:
    types:
      - created

jobs:
  build_unitypackage:
    name: Build .unitypackage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Get Version from tag
        id: version
        env:
          GITHUB_REF: ${{ github.ref }}
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

      - uses: actions/cache@v2
        with:
          path: Unity.AlgoSdk/Library
          key: Library-build_unitypackage-2021.2.13f1-Unity.AlgoSdk-StandaloneLinux64
          restore-keys: |
            Library-build_unitypackage-2021.2.13f1-Unity.AlgoSdk-

      - name: Package .unitypackage
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2020 }}
        with:
          targetPlatform: StandaloneLinux64
          unityVersion: 2021.2.13f1
          projectPath: Unity.AlgoSdk
          buildMethod: UnityPackage.Build
          versioning: None
          allowDirtyBuild: true

      - name: Move .unitypackage for artifacting
        run: |
          mkdir dist
          mv Unity.AlgoSdk/unity-algorand-sdk.unitypackage dist/unity-algorand-sdk-${{ steps.version.outputs.version }}.unitypackage

      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: Add .unitypackage to Release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*.unitypackage
